<?xml version="1.0" ?>
<robot name="balboa" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find balboa_description)/urdf/common_properties.urdf.xacro"/>
  <xacro:include filename="$(find balboa_description)/urdf/wheel.urdf.xacro"/>

  <xacro:property name="body_x" value="${0.5*cm2m}" />
  <xacro:property name="body_y" value="${3*cm2m}" />
  <xacro:property name="body_z" value="${2*cm2m}" />
  <xacro:property name="imu_x" value="${0.01*cm2m}" />
  <xacro:property name="imu_y" value="${0.01*cm2m}" />
  <xacro:property name="imu_z" value="${0.01*cm2m}" />
  <xacro:property name="wheel_radius" value="${1*cm2m}" />
  <xacro:property name="wheel_mass" value="0.5" />
  <xacro:property name="wheel_z_offset" value="${0.5*cm2m}" />
  <xacro:property name="wheel_width" value="${0.1*cm2m}" />
  <xacro:property name="encoder_resolution" value="1440" />
  <xacro:property name="vel_update_rate" value="100" />

  <link name="origin_link" />

  <joint name="origin_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius - wheel_z_offset}" rpy="0 0 0"/>
    <parent link="origin_link"/>
    <child link="base_link"/>
  </joint>

  <!-- Create 3 base definition-->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 ${0*deg2rad} 0"/>
      <geometry>
        <mesh filename="file://$(find balboa_description)/meshes/body.stl" />
      </geometry>
    </visual>
    <collision name="balboa_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find balboa_description)/meshes/body.stl" />
      </geometry>
    </collision>
    <xacro:inertial_cuboid_with_pose mass="1.0" x="${body_x}" y="${body_y}" z="${body_z}">
      <origin xyz="${body_x/2} ${body_y/2} ${body_z/2}" />
      <!-- <origin xyz="0 0 0" /> -->
    </xacro:inertial_cuboid_with_pose>
  </link>

  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="imu_link"/>
  </joint>

  <gazebo reference="imu_joint">
    <preserveFixedJoint>true</preserveFixedJoint>
  </gazebo>

  <link name="imu_link">
    <xacro:inertial_dummy />
  </link>

  <!-- IMU -->
<gazebo reference="imu_link">
    <sensor name="balboa_imu" type="imu">
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <plugin name="balboa_imu" filename="libgazebo_ros_imu_sensor.so">
            <ros>
                <namespace>imu</namespace>
                <remapping>~/out:=data</remapping>
            </ros>
            <initial_orientation_as_reference>false</initial_orientation_as_reference>
        </plugin>
    </sensor>
</gazebo>

  <!-- Wheels -->
  <gazebo>
    <plugin name="gazebo_diffdrive" filename="libgazebo_ros_diffdrive_controller.so">
      <wheel_radius>${wheel_radius}</wheel_radius>
      <wheel_distance>${wheel_width + body_y}</wheel_distance>
      <encoder_resolution>${encoder_resolution}</encoder_resolution>
      <vel_update_rate>${vel_update_rate}</vel_update_rate>
    </plugin>
  </gazebo>

  <!-- Left wheel -->
  <xacro:wheel name="left" width="${wheel_width}" radius="${wheel_radius}" mass="${wheel_mass}" parent_link="base_link">
    <origin xyz="0 ${(body_y+wheel_width)/2} ${wheel_z_offset}" rpy="${-pi/2} 0 0"/>
  </xacro:wheel>

  <!-- Right wheel -->
  <xacro:wheel name="right" width="${wheel_width}" radius="${wheel_radius}" mass="${wheel_mass}" parent_link="base_link">
    <origin xyz="0 ${-(body_y+wheel_width)/2} ${wheel_z_offset}" rpy="${-pi/2} 0 0"/>
  </xacro:wheel>

  <!-- Ground truth pose -->
  <gazebo>
    <plugin name="gazebo_ros_p3d_robot" filename="libgazebo_ros_p3d.so">
      <ros>
        <namespace>/</namespace>
        <remapping>odom:=sim_ground_truth_pose</remapping>
      </ros>
      <body_name>origin_link</body_name>
      <frame_name>world</frame_name>
      <update_rate>62</update_rate>
      <xyz_offset>0 0 0</xyz_offset>
      <rpy_offset>0.0 0.0 0.0</rpy_offset>
      <gaussian_noise>0.0</gaussian_noise>
    </plugin>
  </gazebo>

</robot>
